
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
    *
FROM
    (SELECT 
        customer_id, gender, discount_applied, purchase_amount
    FROM
        customer
    WHERE
        discount_applied = 'Yes') AS sq1
WHERE
    purchase_amount > (SELECT 
            AVG(purchase_amount)
        FROM
            customer);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_product_rating
FROM
    customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amt
FROM
    customer
WHERE
    shipping_type IN ('standard' , 'express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
    subscription_status,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100 * SUM(discount_applied = 'Yes') / COUNT(*), 2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

WITH customer_type as
(SELECT 
    customer_id,
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM
    customer)
SELECT 
    customer_segment, COUNT(*) AS total_counts
FROM
    customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category? 

WITH item_counts as 
					(SELECT category,
                    item_purchased,
                    count(customer_id) as total_orders,
					row_number() over (partition by category order by  count(customer_id) desc) as item_rank
					FROM customer
					group by category ,item_purchased)
SELECT 
    item_rank, category, item_purchased, total_orders
FROM
    item_counts
WHERE
    item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyers
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group, SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY age_group
ORDER BY total_revenue;
